<option value="en" selected="selected">English, US</option>
<option value="en-GB">English, UK</option>
<option value="af">Afrikaans</option>
<option value="ar">Arabic</option>
<option value="bg">Bulgarian</option>
<option value="zh-CN">Chinese Simplified</option>
<option value="zh-TW">Chinese Traditional</option>
<option value="hr">Croatian</option>
<option value="cs">Czech</option>
<option value="da">Danish</option>
<option value="nl">Dutch</option>
<option value="en-ID">English, Indonesia</option>
<option value="et">Estonian</option>
<option value="fi">Finnish</option>
<option value="fr">French</option>
<option value="de">German</option>
<option value="el">Greek</option>
<option value="he">Hebrew</option>
<option value="hu">Hungarian</option>
<option value="is">Icelandic</option>
<option value="id">Indonesian</option>
<option value="ga-IE">Irish</option>
<option value="it">Italian</option>
<option value="ja">Japanese</option>
<option value="ko">Korean</option>
<option value="lv">Latvian</option>
<option value="lt">Lithuanian</option>
<option value="ms">Malay</option>
<option value="mi">Maori</option>
<option value="mk">Macedonian</option>
<option value="mn">Mongolian</option>
<option value="no">Norwegian</option>
<option value="fa">Persian</option>
<option value="pl">Polish</option>
<option value="pt-PT">Portuguese</option>
<option value="pt-BR">Portuguese, Brazilian</option>
<option value="ro">Romanian</option>
<option value="ru">Russian</option>
<option value="sr-CS">Serbian (Latin)</option>
<option value="sl">Slovenian</option>
<option value="es-ES">Spanish</option>
<option value="es-CO">Spanish, Colombia</option>
<option value="es-VE">Spanish, Venezuela</option>
<option value="sv-SE">Swedish</option>
<option value="tl">Tagalog</option>
<option value="ta">Tamil</option>
<option value="th">Thai</option>
<option value="tr">Turkish</option>
<option value="uk">Ukranian</option>
<option value="vi">Vietnamese</option>
<option value="zu">Zulu</option>